### ISSUE TITLE
Markdown Formatting in Notes: Yay or Nay?

### ISSUE THREAD

**Issue by brad-newman** [CooleyLLP/seriesseed#1]
If you look closely, you'll notice that the notes financing documents have additional markdown formatting compared to the equity financing documents (for example, defined terms in the equity documents look like "This" but in the notes look like "_**This**_").  This formatting approximates what we offer in the [Cooley GO Docs generator](https://www.cooleygo.com/documents/series-seed-notes-financing-package/) output. 

However, I'm happy to remove this fancy formatting if folks feel that it's unnecessary/distracting. Just leave a comment to let me know!

**Comment by derekcolla** [comment]
I like the additional formatting. Helps the defined terms stand out and you can find them easier when doing a quick scan of the documents.

**Comment by brad-newman** [comment]
@derekcolla thanks for the feedback!

**Comment by Zulhelmy100** [comment]
@brad-newman  ya same goes to me..i like the additional formatting too...

**Comment by brad-newman** [comment]
@Zulhelmy100 great, thanks to you as well for taking the time to voice your approval!
