### ISSUE TITLE
Section [[7.1][7.2(a)]] [or Section 7.1(c)]

### ISSUE THREAD

**Issue by HazardJ** [CooleyLLP/seriesseed#7]
In the Preferred Stock Investment Agreement,  the phrase "Section [[7.1][7.2(a)]] [or Section 7.1(c)]" seems muddled.  There is no Section 7.2.  Section 7.1 (the only subsection of Section 7) has three bracketed (optional) subsubsections - 7.1(a), 7.1(b) and 7.1(c).

**Comment by brad-newman** [comment]
Hi @HazardJ - 7.1 has no subsections if there are only Common Board Members, however if there are either Series Seed and/or  Mutual Consent Board Members, then it becomes 7.1(a), (b) and/or (c).

You are correct that "7.2(a)" should read "7.**1**(a)", and I will get that fixed soon.  Thanks for spotting!
